ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "billToName" text;
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "billToEmail" text;
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "billToPhone" text;

ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "billToName" text;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "billToEmail" text;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "billToPhone" text;
